In [1]:
import pandas as pd
import sklearn
import sklearn.decomposition
import numpy as np

In [2]:
close_prices = pd.read_csv("close_prices.csv")

In [3]:
djia_index = pd.read_csv("djia_index.csv")

In [135]:
close_prices.head(1)

date        AXP          BA        CAT   CSCO         CVX         DD  \
0  2013-09-23  76.440002  117.510002  85.029999  24.27  125.519997  59.409999   

     DIS         GE      GS  ...          PFE         PG          T  \
0  64.75  24.280001  165.25  ...    28.799999  79.279999  34.220001   

         TRV    UNH         UTX           V     VZ        WMT    XOM  
0  86.379997  71.82  109.419998  196.240005  47.98  76.419998  87.75  

[1 rows x 31 columns]

In [138]:
djia_index.head(1)

date          ^DJI
0  2013-09-23  15401.379883

In [57]:
pca = sklearn.decomposition.PCA(n_components=10)

In [84]:
X = np.array(close_prices.iloc[:,1:])

In [127]:
U = pca.fit_transform(X)

In [86]:
pca.explained_variance_ratio_ 

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

In [137]:
sum(pca.explained_variance_ratio_[:4])

0.9277429537836401

In [104]:
np.corrcoef(U[:,0], djia_index.iloc[:,1])

array([[1.        , 0.90965222],
       [0.90965222, 1.        ]])

In [132]:
max(pca.components_[0])

0.5796839457473606

In [134]:
pca.components_[0]

array([ 1.61383840e-02,  1.20644923e-01, -5.16612711e-02,  5.04842369e-02,
       -1.25859933e-01,  1.14089567e-01,  2.33906290e-01, -6.20513749e-03,
        2.51227032e-01,  2.88996029e-01, -2.64998795e-01,  9.31320168e-02,
        9.13948403e-02,  4.69879340e-02,  2.90549417e-02, -2.61068828e-02,
        3.29615584e-01,  7.13897133e-02,  7.62295699e-02,  2.11888868e-01,
        2.30922941e-02,  7.77316954e-02, -7.20594590e-03,  1.89479745e-01,
        3.21564017e-01,  5.36834873e-02,  5.79683946e-01,  1.09122230e-04,
        8.71614334e-02, -4.29421420e-02])